# Generated by Django 4.2 on 2023-05-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionViajes', '0002_viaje_plazas_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
