# Generated by Django 4.2 on 2023-05-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionViajes', '0003_viaje_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
