# Generated by Django 4.2 on 2023-05-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionViajes', '0004_viaje_eliminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='eliminado',
        ),
    ]
