# Generated by Django 4.0.4 on 2022-06-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatchViajesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='conductor',
        ),
        migrations.DeleteModel(
            name='PasajerosViaje',
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
